### ISSUE TITLE
Minor Typo in pre-install.inventory.ini

### ISSUE THREAD

**Issue by kongxingagit** [sassoftware/virk#100]
"## this is a sample inventory which contains all possible Host Groups for Viya 3.3"
should be 

"## this is a sample inventory which contains all possible Host Groups for Viya 3.4" when on the 3.4 branch, but it still says Viya 3.3.

This caused some doubt and confusion in our install process.

**Comment by kevinlinglesas** [comment]
This issue has been addressed in [Initial Release](https://github.com/sassoftware/viya-ark/releases/tag/v0.1) of [Viya ARK](https://github.com/sassoftware/viya-ark) project.
