### ISSUE TITLE
yum_repo check succeeds when curl times out

### ISSUE THREAD

**Issue by benformosa** [sassoftware/virk#101]
The 'Trying to hit the SAS yum repository' task may succeed when the repository cannot be reached.

The task checks for the string `Connect` in stderr, which will be present if the connection fails with the message `Connection timed out`.

https://github.com/sassoftware/virk/blob/76f462450015636f4453d35487042d3110794d63/playbooks/pre-install-playbook/roles/virk.preinstall/tasks/pre.network_and_bandwidth_check.yml#L52

Here's the output from curl timing out:

```
$ curl -v -k https://ses.sas.download
* About to connect() to ses.sas.download port 443 (#0)
*   Trying 149.173.160.82...
* Connection timed out
* Failed connect to ses.sas.download:443; Connection timed out
* Closing connection 0
curl: (7) Failed connect to ses.sas.download:443; Connection timed out
```

Additionally, Ansible issues a warning to consider using [get_url](https://docs.ansible.com/ansible/latest/modules/get_url_module.html) instead of curl.
```
 [WARNING]: Consider using the get_url or uri module rather than running curl.  If you need to use command because get_url or uri is insufficient you can add warn=False to this command task or set
command_warnings=False in ansible.cfg to get rid of this message.
```

Ignoring HTTPS certificates is probably also not ideal.

**Comment by kevinlinglesas** [comment]
Connection refused scenario results in the same behavior.

ok: [deployTarget] => (item=ses.sas.download) => {
    "changed": false,
    "cmd": "curl -v -k https://ses.sas.download/",
    "delta": "0:00:01.031195",
    "end": "2019-02-15 14:05:37.047544",
    "failed_when_result": false,
    "invocation": {
        "module_args": {
            "_raw_params": "curl -v -k https://ses.sas.download/",
            "_uses_shell": true,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "warn": true
        }
    },
    "item": "ses.sas.download",
    "msg": "non-zero return code",
    "rc": 7,
    "start": "2019-02-15 14:05:36.016349",
    "stderr": "* About to connect() to ses.sas.download port 443 (#0)\n*   Trying 149.173.160.82... Connection refused\n* couldn't connect to host\n* Closing connection #0\n\ncurl: (7) couldn'\
t connect to host",
    "stderr_lines": [
        "* About to connect() to ses.sas.download port 443 (#0)",
        "*   Trying 149.173.160.82... Connection refused",
        "* couldn't connect to host",
        "* Closing connection #0",
        "",
        "curl: (7) couldn't connect to host"
    ],

**Comment by kevinlinglesas** [comment]
This issue has been addressed in [New features added and more issues addressed.](https://github.com/sassoftware/viya-ark/releases/tag/v0.2) of [Viya ARK](https://github.com/sassoftware/viya-ark) project.  See DEPENB-1551 release note.
