### ISSUE TITLE
name of 'Disable SELinux' task is inaccurate

### ISSUE THREAD

**Issue by benformosa** [sassoftware/virk#102]
The task `Disable SELinux (will only take effect after a reboot)` does not disable SELinux as the name implies, but sets it to Permissive.

https://github.com/sassoftware/virk/blob/76f462450015636f4453d35487042d3110794d63/playbooks/pre-install-playbook/roles/virk.preinstall/tasks/pre.selinux_config.yml#L36:L46

**Comment by kevinlinglesas** [comment]
This issue has been addressed in [Initial Release](https://github.com/sassoftware/viya-ark/releases/tag/v0.1) of [Viya ARK](https://github.com/sassoftware/viya-ark) project.  See DEPENB-1552 release note.
