### ISSUE TITLE
Minimum Ansible Version 3.4 is Incorrect

### ISSUE THREAD

**Issue by AWSmith0216** [sassoftware/virk#106]
Hey,

The Viya 3.4 pre install playbook currently asserts that the minimum ansible version is 2.4. However, the official documentation states it is 2.3: https://support.sas.com/en/documentation/third-party-software-reference/viya/34/support-for-operating-systems.html.

The actual deployment playbook itself also doesn't complain about using 2.3 if deploying Viya 3.4. Could the minimum version be corrected?

Thanks

**Comment by kevinlinglesas** [comment]
his issue has been addressed in [Viya34-ark-1.4](https://github.com/sassoftware/viya-ark/releases/tag/Viya34-ark-1.4) release of [Viya ARK](https://github.com/sassoftware/viya-ark).  

1. The minimum version of Ansible supported in SAS Viya 3.4 and the verification of the minimum Ansible version in the pre-install playbook are now consistent.   Ansible 2.5 - 2.7.

2. The documentation link mentioned in this issue has also been updated to reflect this range of Ansible versions.
