### ISSUE TITLE
pre.semaphores_config.yml Should set semaphore values only if they are presently lower than what is recommended

### ISSUE THREAD

**Issue by Carus11** [sassoftware/virk#108]
Feature Request:
The file pre.semaphores_config.yml will set the semaphore values to a specific value, even if the administrator has previously set them higher.

I would like the script to set those values only if the system's present value is lower than what is documented as a minimum, and not overwrite them if higher.

Thanks

**Comment by Carus11** [comment]
Something like the following could be used to pull the individual values into json for ansible to work with

`cat /proc/sys/kernel/sem | awk '{printf "{\"SEMMSL\": \"%s\", \"SEMMNS\": \"%s\", \"SEMOPM\": \"%s\", \"SEMMNI\": \"%s\"}\n",$1,$2,$3,$3}'`

**Comment by kevinlinglesas** [comment]
The [Viya35-ark-1.0](https://github.com/sassoftware/viya-ark/releases/tag/Viya35-ark-1.0) contains an enhancement related to this issue.   See [CHANGELOG](https://github.com/sassoftware/viya-ark/blob/master/CHANGELOG.md) and look for _**DEPENB-1578**_

**>>>>Note well this virk repo is deprecated.  Use viya-ark repo.<<<<**
