### ISSUE TITLE
systemd-219-67 is not compatible with SAS Viya deployment

### ISSUE THREAD

**Issue by dotnet007** [sassoftware/virk#110]
Virk requires to update to the latest version of systemd (in  virk/playbooks/pre-install-playbook/roles/viya-ark.preinstall/tasks/pre.required_packages_config.yml), but the current version of systemd 219-67 is not compatible with SAS Viya, or at least thrown the following error in the deployment (site.yml playbook):

The RabbitMQ service sas-viya-rabbitmq-server-default could not be started.", "Tue Aug 13 13:56:43 UTC 2019 setup_rabbit_cluster Returned status was 1
I will sugest to not force to update to the latest version, only validate if is in the minimal required version.

Thank you.

**Comment by kevinlinglesas** [comment]
@dotnet007 please take notice of the DEPRECATION NOTICE in the README for virk repo and begin using the new viya-ark repo.  This repo is not being updated anymore.
To the point of the issue you raise, a workaround is available now in viya-ark master per [Viya34-ark-1.6 release](https://github.com/sassoftware/viya-ark/releases/tag/Viya34-ark-1.6)
