### ISSUE TITLE
[WARNING]: Could not match supplied host pattern, ignoring: sas-all

### ISSUE THREAD

**Issue by j08rebelo** [sassoftware/virk#111]
Using the Virk tool to restart services, i'm seeing the following message:
[WARNING]: Could not match supplied host pattern, ignoring: sas-all

which leads to:

TASK [Stop SAS HTTP proxy service] ****************************************************************************************************************************************
fatal: [deployTarget]: FAILED! => {"msg": "The conditional check 'psflag.stdout != \"\" and deployhostnum | int != 1' failed. The error was: error while evaluating conditional (psflag.stdout != \"\" and deployhostnum | int != 1): 'psflag' is undefined\n\nThe error appears to have been in '/sas/upgrade7/sas_viya_playbook/virk/playbooks/viya-mmsu/viya-services-stop.yml': line 67, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n    - name: Stop SAS HTTP proxy service\n      ^ here\n"}

NO MORE HOSTS LEFT ********************************************************************************************************************************************************

PLAY RECAP ****************************************************************************************************************************************************************
deployTarget               : ok=0    changed=0    unreachable=0    failed=1

SAS Support track 7612867238, i see a comment saying "The VIRK preinstall playbook is the old version that looked for sas-all, and is not finding it in your newer playbook/inventory file". 

Is there a new version where this issue is fixed?

**Comment by erharb** [comment]
starting with orchestration CLI released at 19w34 all hyphenated host groups in the inventory file were changed to underscores (sas-all became sas_all). The Viya ARK was also updated to handle that, please make sure you are using the latest Viya ARK release.

**Comment by j08rebelo** [comment]
thank you. Consider this question closed.

A quinta, 26/09/2019, 16:14, Eric Harbeston <notifications@github.com>
escreveu:
