### ISSUE TITLE
Version check of systemd is not reflective of the documentation

### ISSUE THREAD

**Issue by erwangranger** [sassoftware/virk#12]
The deployment guide states that:

> On Linux 7.x, verify that the systemd package on each machine is at version 219-30 or later. Run the following command:
> $ rpm -qa | grep systemd

However, the code in the playbook does not check for "at least" but instead checks for exact equality. 

On [line 77](https://github.com/sassoftware/virk/blob/21b3f0be02ea75001027714bd28cab7c635bcff3/playbooks/pre-install-playbook/roles/virk.preinstall/tasks/pre.required_packages_config.yml#L77), we gather:
`systemctl --version | head -n 1` . 
Then on [line 88](https://github.com/sassoftware/virk/blob/21b3f0be02ea75001027714bd28cab7c635bcff3/playbooks/pre-install-playbook/roles/virk.preinstall/tasks/pre.required_packages_config.yml#L88) we check that:
`systemd_version.stdout != "systemd 219"`. 

This will eventually fail (when systemd versions get higher than 219). 
Instead we need to capture this as a numeric variable instead and make sure the version is >= 219-30. 

(And while we are at it, we should make the value a variable rather than have hard-coded inside the playbook).

**Comment by screnshaw** [comment]
Is it suitable to derive the full version by running "rpm -qa | grep system" and parsing the package name output, or do you all know of a cleaner way?  Running "systemctl --version" only give the major version number, and I'm trying to research and figure if there is a better way. 

So far I am able to pipe the rpm output to grep and awk to get the minor version number, but it seems a bit choppy.

**Comment by kevinlinglesas** [comment]
This issue was previously addressed by https://github.com/sassoftware/virk/commit/9897cd8b3b2e2a03b53eccad8ccfcf44d3ea34d3 in development of Viya 3.3 functionality.
