### ISSUE TITLE
check that the hostname is valid (RFC952). for example, no underscore. 

### ISSUE THREAD

**Issue by erwangranger** [sassoftware/virk#13]
Hello, 
It's been reported that if the hostname is not compliant with the RFC 952 Specifications, it can lead to issues in the deployment. 
Read [this wikipedia page](https://en.wikipedia.org/wiki/Hostname#Restrictions_on_valid_hostnames) for more details. 
From [this page](https://tools.ietf.org/html/rfc952):
> A "name" (Net, Host, Gateway, or Domain name) is a text string up to 24 characters drawn from the alphabet (A-Z), digits (0-9), minus   sign (-), and period (.).

In the case we have seen, there was an underscore (_) in the name.

**Comment by thpang** [comment]
We could use a regex or something to verify the name is compliant and if not warn the user and stop them until they make the modifications to correct the issue. Thoughts?

**Comment by erwangranger** [comment]
fully in agreement. I had started thinking "detect underscore", but as you say, it's much better to "detect only letters, numbers, dots and dashes". 
I'm guessing that the 24 character limit is "between 2 dots".

**Comment by kevinlinglesas** [comment]
This issue has been addressed in [Initial Release](https://github.com/sassoftware/viya-ark/releases/tag/v0.1) of [Viya ARK](https://github.com/sassoftware/viya-ark) project.  See DEPENB-1392 release note.
