### ISSUE TITLE
Detect public-only IPs

### ISSUE THREAD

**Issue by erwangranger** [sassoftware/virk#16]
Consul has issues starting up when the only IP available is a public-facing IP. 
(see [this issue](https://github.com/hashicorp/consul/issues/725) )
The fix is to use the Consul_bind_adapter like when there are more than one network interface. 

We should try to detect public IPs (using a range?) and output a message similar to what is in [this existing check](https://github.com/sassoftware/virk/blob/viya-3.3/playbooks/pre-install-playbook/roles/virk.preinstall/tasks/pre.network_and_bandwidth_check.yml#L32-L37)

**Comment by williamsas** [comment]
I'm running into an issue with a local install where the hosts file doesn't have the hostname mapped to the IP address. It would be good to add this check if it's a local install. 

Create Cert and key
/opt/sas/viya/home/SASSecurityCertificateFramework/bin/sas-crypto-management req-vault-cert --common-name confiotvaesp.unx.sas.com --out-crt /opt/sas/viya/config/etc/SASSecurityCertificateFramework/tls/certs/sasdatasvrc/postgres/pgpool0/sascert.pem --out-key /opt/sas/viya/config/etc/SASSecurityCertificateFramework/private/sasdatasvrc/postgres/pgpool0/saskey.pem --san-dns localhost --san-dns confiotvaesp.unx.sas.com --san-dns confiotvaesp --san-dns confiotvaesp.unx.sas.com --san-ip # 127.0.0.1,172.20.70.67 --san-ip fe80::250:56ff:fe93:16be --vault-token /opt/sas/viya/config/etc/SASSecurityCertificateFramework/tokens/pgpoolc/default/vault.token --vault-cafile /opt/sas/viya/config/etc/SASSecurityCertificateFramework/cacerts/trustedcerts.pem

**Comment by thpang** [comment]
This issue is related to #46 closing this one.
