### ISSUE TITLE
add jq and redhat-lsb-core yum packages installation

### ISSUE THREAD

**Issue by raphaelpoumarede** [sassoftware/virk#17]
jq (from EPEL repo) is required to parse JSON message when SAS CLI is configured for it and is called during the MT onboarding (and potentially other things). The other package : redhat-lsb-core is also required when running the MT onboarding playbook.
Both packages should exist on "CommandLine" host group.

**Comment by erwangranger** [comment]
I've been informed that the documentation now has simple [set of command](https://go.documentation.sas.com/?cdcId=calcdc&cdcVersion=3.4&docsetId=dplyml0phy0lax&docsetTarget=n0zjykknqs5ln6n1292uvye8ucrb.htm&locale=en#n0rb33plg9ipqgn11a1dboifeiof) to get jq from GitHub. 
That should make it easier to add a task to the VIRK pre-req playbook to perform the change.

**Comment by thpang** [comment]
We will not pursue the addition of these items in the pre-install checklist.
