### ISSUE TITLE
Verify permissions in /opt/sas

### ISSUE THREAD

**Issue by henriquevaskys** [sassoftware/virk#19]
Hi

I was troubleshooting a failed install of Viya, and the cause was:

- Original /opt was deleted and substituted by a symbolic link to /data/sas (not a real problem, but not recommended at all)
- permission on /data was 700 for sas user only, and permission on /opt/sas was 755.

My suggestion is

- Verify if /opt is a physical directory (I know there is check if / and /opt/sas are not in the same partition)
- Verify permissions for both /opt and /opt/sas (755 maybe?)

If you have any doubts, fell free to contact me directly.

Cheers,
Henri

**Comment by kevinlinglesas** [comment]
This issue has been addressed in [Viya34-ark-1.4](https://github.com/sassoftware/viya-ark/releases/tag/Viya34-ark-1.5) release of[ Viya ARK](https://github.com/sassoftware/viya-ark).
