### ISSUE TITLE
Check path for command when elevating permissions

### ISSUE THREAD

**Issue by jlwalke2** [sassoftware/virk#22]
Can the playbook perform a reasonable amount of validation to ensure that commands executed during the install will actually be found when Ansible users become: <user>?

In secured environments /sbin may not be included in the PATH when using privilege escalation.  This is true of both VIRK (/bin/sh sshd -T) and the Viya install process itself (/bin/sh service <foo>).  Performing an initial check that such commands can be found when using the selected become-method would be extremely helpful.

**Comment by AlissaSchleich** [comment]
This request will not be implemented.   Customer environments are too variable to try and pin down command paths.
