### ISSUE TITLE
convert fail tasks to assert tasks for better user experience

### ISSUE THREAD

**Issue by erwangranger** [sassoftware/virk#57]
In checks such as https://github.com/sassoftware/virk/blob/ee1e6f9f3c51e5ba495f95cd341424e1ee6c5a8c/playbooks/pre-install-playbook/roles/virk.preinstall/tasks/pre.third_party_check.yml#L22 
, we use the fail module. 
When the condition is not met, the task get skipped. 

I find that the user experience is better when using the ansible "assert" module. The assertion either passes or fails, and if it fails, we can output a nice message. 

For example:  https://github.com/sassoftware/virk/blob/ee1e6f9f3c51e5ba495f95cd341424e1ee6c5a8c/playbooks/pre-install-playbook/roles/virk.preinstall/tasks/pre.cpu_check.yml#L35

Skipped tasks should probably be reserved for things that are not for the right OS, for example. 

(also, skipped tasks do not show up in the counts at play recap).

**Comment by kevinlinglesas** [comment]
This issue has been addressed [Release Viya34-ark-1.0](https://github.com/sassoftware/viya-ark/releases/tag/Viya34-ark-1.0).  See See DEPENB-1367 release note.
