### ISSUE TITLE
specify that virk is linux only

### ISSUE THREAD

**Issue by raphaelpoumarede** [sassoftware/virk#75]
Very soon Viya will be available for Windows. Nothing in the README states that the tools here are for linux version of Viya only. Unless a windows virk (providing Powershell scripts for example for pre-reqs) is planned, it should be specified in the README that VIRK is Linux only.
thanks

**Comment by cjdinger** [comment]
There is a similar project available for Windows -- probably worth mentioning in the README:

https://github.com/sassoftware/sas-wvda

**Comment by thpang** [comment]
@raphaelpoumarede we are in the process of developing similar scripts for Windows written in PowerShell. The general thought is that most folks working with Ansible are doing so in a Linux environment and folks working with PowerShell are in a Windows environment. Once these PowerShell scripts are ready they'll be listed in a directory labeled 'powershell'. I am sure for some that will be sufficient, but to your point, I believe we'll need to let folks know the Ansible scripts are not usable in a Windows environment and are targeted toward Linux operating system.

**Comment by kevinlinglesas** [comment]
This issue has been addressed in [Viya34-ark-1.4](https://github.com/sassoftware/viya-ark/releases/tag/Viya34-ark-1.4) release of [Viya ARK](https://github.com/sassoftware/viya-ark).   A link to SAS Viya Deployment Assistant for Windows has been added to the [Viya ARK README](https://github.com/sassoftware/viya-ark/blob/master/README.md).
