### ISSUE TITLE
Relative file path in the start stop scripts

### ISSUE THREAD

**Issue by Carus11** [sassoftware/virk#76]
When running the stop script an error appears:

`TASK [Stop CAS server] *********************************************************************************************************************************************************************************
changed: [hqca-cas]
ERROR! vars file ../../../vars.yml was not found
`

**Comment by thpang** [comment]
Hi @Carus11. Given your initial comment that explains why you are looking for the vars.yaml file with a relative path, we had given quite a lot of thought to this prior to releasing the code. The general decision to have the service-management playbook live in within each sas_viya_playbook area was to ensure that the customer knows that the script itself is tied to one's current playbook with a need for the vars.yaml created during orchestration. We will take a note here and see what/if changes will be made in the future to make this script independent of a Viya playbook.

**Comment by Carus11** [comment]
I think the direction in Viya 3.3 was to ln -s the playbooks into the sas_viya_playbook directory. In 3.4 it seems to work when I place the entire virk folder into the playbook directory so that file the looks for vars.yml is three levels up. 

I think if a specific directory layout is a requirement for the successful run of the script, then it should be noted on in the readme.

Quite often though I find we are running the pre-install playbooks before generating the main sas_viya_playbook, as part of the pre-install projects steps before the official installation phase of the projects start.

**Comment by thpang** [comment]
The pre-install scripts themselves do not have to placed in any particular location; however, the service-management scripts must be placed under your Viya installation post playbook generation.

If you look at the README file for the service management scripts, located here:

https://github.com/sassoftware/virk/tree/viya-3.4/playbooks/service-management

you can see in the second bullet, the text does explain this set of scripts must be placed under your Viya deployment location.

The other scripts are completely independent of a Viya installation and do not need Viya installed in any form unless they state they are needed in their respective README files.

So once you've cloned the repo you can copy the subsequent directories to their needed locations, independently of each other. These are all separate tool sets and are not coupled to each other in any way.

Glad to see you are using the script pre-installation to help with your installation that was their intention from the beginning.

**Comment by Carus11** [comment]
Thanks @thpang, I apologize, I missed that readme file.
