### ISSUE TITLE
plans to have an ESP stand-alone version of VIRK?

### ISSUE THREAD

**Issue by raphaelpoumarede** [sassoftware/virk#84]
Is there a plan to have a version of Virk for stand-alone ESP installation ? 
It would be great to have a tag to use VIRK to only apply ESP 5.2 pre-requisites (that are described in the official ESP 5.2 Deployment Guide).
thanks !

**Comment by AlissaSchleich** [comment]
There are no plans at this time to have a version of Virk for stand-alone ESP installation
