### ISSUE TITLE
add LOCALE checking to the VIRK pre-req playbooks. 

### ISSUE THREAD

**Issue by erwangranger** [sassoftware/virk#86]
Not all locales are supported. The list of supported locales is available [here.](https://go.documentation.sas.com/?cdcId=pgmsascdc&cdcVersion=9.4_3.4&docsetId=nlsref&docsetTarget=p0kcqbj7zsjq23n1lfyrcgtwiy5q.htm&locale=en) .

The deployment will not fail, but parts of Viya will not function properly, and this will lead to issues and wasted time. 

Here is an example: 
In my system, I get:
```bash
[me@server]$ locale | grep LANG
LANG=en_US.UTF-8
[me@server]
```

A colleague had a locale of en_DK.UTF-8. That one is not supported (see list above). 

We should detect in advance that the server has an unsupported locale, and trigger an error.

**Comment by kevinlinglesas** [comment]
This issue has been addressed in [New features added and more issues addressed.](https://github.com/sassoftware/viya-ark/releases/tag/v0.2) of [Viya ARK](https://github.com/sassoftware/viya-ark) project.  See DEPENB-1370 release note.
