### ISSUE TITLE
SAS VIYA does not start

### ISSUE THREAD

**Issue by JayKyle01** [sassoftware/virk#93]
We are unable to start our SAS VIYA instance. It was working normally, but the servers were rebooted without shutting down Viya.

**The start/stop commands we use are:**

To Start or Stop Viya 3.4
=========================

# read /sas/install/DEV/current/sas_viya_playbook/virk/playbooks/service-management/README.md
# for details

As sas, on the Ansible controller
cd /sas/install/DEV/current/sas_viya_playbook

To stop
-------
1. ansible-playbook virk/playbooks/service-management/viya-services-stop.yml
2. check all servers for zombies
3. ansible-playbook virk/playbooks/service-management/viya-services-status.yml

To Start
--------
1. check all servers for zombies
2. ansible-playbook virk/playbooks/service-management/viya-services-start.yml
3. ansible-playbook virk/playbooks/service-management/viya-services-status.yml

**The error  message from ansible is in the log below:**

[ec2-user@viya-installer sas_viya_playbook]$ ansible-playbook virk/playbooks/service-management/viya-services-start.yml

PLAY [sas-all] ***************************************************************************************************************************************************************************************************************************

TASK [Check the accessibility of the hosts] **********************************************************************************************************************************************************************************************
ok: [viyaWorker1]
ok: [viyaController]
ok: [viyaCore]
ok: [viyaWorker3]
ok: [viyaWorker2]

PLAY [consul] ****************************************************************************************************************************************************************************************************************************

TASK [Start SAS Primary Consul Server] ***************************************************************************************************************************************************************************************************
changed: [viyaCore]

TASK [Start SAS Secret Manager (Vault)] **************************************************************************************************************************************************************************************************
changed: [viyaCore]

PLAY [sas-all:!consul] *******************************************************************************************************************************************************************************************************************

TASK [Start SAS Local Consul Servers] ****************************************************************************************************************************************************************************************************
changed: [viyaController]
changed: [viyaWorker1]
changed: [viyaWorker3]
changed: [viyaWorker2]

PLAY [rabbitmq] **************************************************************************************************************************************************************************************************************************

TASK [Start SAS Message Broker (RabbitMQ)] ***********************************************************************************************************************************************************************************************
changed: [viyaCore]

PLAY [sasdatasvrc] ***********************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************************************************************************
ok: [viyaCore]

TASK [Start SAS Infrastructure Data Server Consul Template] ******************************************************************************************************************************************************************************
changed: [viyaCore] => (item={u'SANMOUNT': u'/opt/sas/viya/config/data/sasdatasvrc', u'NODE_TYPE': u'P', u'NODE_NUMBER': u'0', u'PG_PORT': u'5432', u'SERVICE_NAME': u'postgres'})

TASK [Start SAS Infrastructure Data Server Consul Template] ******************************************************************************************************************************************************************************
changed: [viyaCore] => (item={u'SANMOUNT': u'/opt/sas/viya/config/data/sasdatasvrc', u'NODE_TYPE': u'P', u'NODE_NUMBER': u'0', u'PG_PORT': u'5432', u'SERVICE_NAME': u'postgres'})

PLAY [pgpoolc] ***************************************************************************************************************************************************************************************************************************

TASK [Start SAS Infrastructure Data Server] **********************************************************************************************************************************************************************************************
changed: [viyaCore] => (item=-pgpool0-ct-pcp)
changed: [viyaCore] => (item=-pgpool0-ct-pgpool)
changed: [viyaCore] => (item=-pgpool0-ct-pool_hba)
failed: [viyaCore] (item=) => {"changed": false, "item": "", "msg": "Unable to start service sas-viya-sasdatasvrc-postgres: Job for sas-viya-sasdatasvrc-postgres.service failed because a configured resource limit was exceeded. See \"systemctl status sas-viya-sasdatasvrc-postgres.service\" and \"journalctl -xe\" for details.\n"}

NO MORE HOSTS LEFT ***********************************************************************************************************************************************************************************************************************

PLAY RECAP *******************************************************************************************************************************************************************************************************************************
viyaController             : ok=2    changed=1    unreachable=0    failed=0
viyaCore                   : ok=7    changed=5    unreachable=0    failed=1
viyaWorker1                : ok=2    changed=1    unreachable=0    failed=0
viyaWorker2                : ok=2    changed=1    unreachable=0    failed=0
viyaWorker3                : ok=2    changed=1    unreachable=0    failed=0

[ec2-user@viya-installer sas_viya_playbook]$ ^C 

**The postgres log shows:**

[root@viya-dev-core0 bin]# more /opt/sas/viya/config/var/log/sasdatasvrc/postgres/pgpool0/sas-viya-sasdatasvrc-postgres-service_20181114_090511.log
Successfully retrieved PGUSER from Consul via sas-bootstrap-config
Successfully retrieved PGPASSWORD from Consul via sas-bootstrap-config
Successfully retrieved PGPORT from Consul via sas-bootstrap-config
Successfully retrieved PCPUSER from Consul via sas-bootstrap-config
Successfully retrieved PCPPORT from Consul via sas-bootstrap-config
Successfully retrieved PCPPASSWORD from Consul via sas-bootstrap-config

Start request received at Wed Nov 14 09:05:12 CST 2018
Starting sas-viya-sasdatasvrc-postgres...

/opt/sas/viya/config/data/sasdatasvrc/postgres/pgpool0/startall execution starts, Wed Nov 14 09:05:12 CST 2018
  CONSUL_HTTP_ADDR=https://localhost:8501
  CONSUL_TEMPLATE_OPTIONS=-consul-addr localhost:8501 -consul-ssl -consul-ssl-ca-cert /opt/sas/viya/config/etc/SASSecurityCertificateFramework/cacerts/trustedcerts.pem
Checking Consul is accessibility...
Consul is accessible.
f_set_cluster_var ERROR: pg primary hostname was not found for the postgres cluster in Consul service store
f_set_cluster_var ERROR: Unable to set CLUSTER_PG_PRIMARY_HOSTNAME variable
/opt/sas/viya/home/bin/sas-bootstrap-config --output json catalog service postgres...
{
    "items": [
        {
            "address": "10.123.35.254",
            "node": "viya-dev-core0.fcc.ca",
            "serviceAddress": "ip-10-123-35-254.fcc.ca",
           "serviceEnableTagOverride": false,
            "serviceID": "postgres-pgpool0",
            "serviceName": "postgres",
            "servicePort": 5431,
            "serviceTags": [
                "pgpool:postgres",
                "public",
                "pgpool",
                "ssl"
            ],
            "taggedAddresses": {
                "lan": "10.123.35.254",
                "wan": "10.123.35.254"
            }
        }
    ]
}
export CLUSTER_PG_NODE_NAME_LIST=''
export CLUSTER_PG_NODE_NUMBER_LIST=''
export CLUSTER_PG_NODE_COUNT=
export CLUSTER_PG_PORT_LIST=''
export CLUSTER_PG_DATA_DIRECTORY_LIST=''
export CLUSTER_PG_SERVICE_NODE_LIST=''
export CLUSTER_PG_HOST_LIST=''
export CLUSTER_PG_PRIMARY_HOSTNAME=
export CLUSTER_PG_PRIMARY_PORT=
export CLUSTER_PG_PRIMARY_NODE_NUMBER=
export CLUSTER_POOL_NODE_NAME_LIST=''
export CLUSTER_POOL_NODE_COUNT=
export CLUSTER_POOL_PCP_PORT_LIST=''
export CLUSTER_POOL_PORT_LIST=''
export CLUSTER_POOL_DIRECTORY_LIST=''
export CLUSTER_POOL_SERVICE_LIST=''
export CLUSTER_POOL_HOST_LIST=''
export CLUSTER_POOL_PRIMARY_HOSTNAME=ip-10-123-35-254.fcc.ca
export CLUSTER_POOL_PRIMARY_PORT=
export CLUSTER_POOL_PRIMARY_NODE_NUMBER=
ERROR: f_set_cluster_var function failed
ERROR: Unable to start or stop the postgres cluster
Failure

ERROR: Cluster start failed. Please review the log file.
/opt/sas/viya/config/var/log/sasdatasvrc/postgres/pgpool0/sas-viya-sasdatasvrc-postgres-service_20181114_090511.log
Start request processed at Wed Nov 14 09:05:13 CST 2018

[

**Journal -xe shows:**

[root@viya-dev-core0 bin]# journalctl -xe
-- Subject: Unit session-c209.scope has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit session-c209.scope has finished starting up.
--
-- The start-up result is done.
Nov 14 09:05:11 viya-dev-core0.fcc.ca su[33401]: pam_unix(su:session): session opened for user sas by (uid=0)
Nov 14 09:05:11 viya-dev-core0.fcc.ca su[33401]: pam_unix(su:session): session closed for user sas
Nov 14 09:05:11 viya-dev-core0.fcc.ca sas-viya-sasdatasvrc-postgres[33362]: 2018-11-14 09:05:11 AM CST: Checking for Consul agent and leader, waiting...
Nov 14 09:05:11 viya-dev-core0.fcc.ca sas-viya-sasdatasvrc-postgres[33362]: Consul agent and leader are up.
Nov 14 09:05:11 viya-dev-core0.fcc.ca sas-viya-sasdatasvrc-postgres[33362]: Consul is accessible.
Nov 14 09:05:11 viya-dev-core0.fcc.ca sas-viya-sasdatasvrc-postgres[33362]: Vault is accessible.
Nov 14 09:05:12 viya-dev-core0.fcc.ca sas-viya-sasdatasvrc-postgres[33362]: Starting sas-viya-sasdatasvrc-postgres...
Nov 14 09:05:12 viya-dev-core0.fcc.ca su[33621]: (to sas) root on none
Nov 14 09:05:12 viya-dev-core0.fcc.ca systemd[1]: Started Session c210 of user sas.
-- Subject: Unit session-c210.scope has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit session-c210.scope has finished starting up.
--
-- The start-up result is done.
Nov 14 09:05:12 viya-dev-core0.fcc.ca su[33621]: pam_unix(su:session): session opened for user sas by (uid=0)
Nov 14 09:05:13 viya-dev-core0.fcc.ca su[33621]: pam_unix(su:session): session closed for user sas
Nov 14 09:05:13 viya-dev-core0.fcc.ca sas-viya-sasdatasvrc-postgres[33362]: Failure
Nov 14 09:05:13 viya-dev-core0.fcc.ca sas-viya-sasdatasvrc-postgres[33362]: ERROR: Cluster start failed. Please review the log file.
Nov 14 09:05:13 viya-dev-core0.fcc.ca sas-viya-sasdatasvrc-postgres[33362]: /opt/sas/viya/config/var/log/sasdatasvrc/postgres/pgpool0/sas-viya-sasdatasvrc-postgres-service_20181114_090511.log
Nov 14 09:05:13 viya-dev-core0.fcc.ca systemd[1]: PID file /opt/sas/viya/config/data/sasdatasvrc/postgres/pgpool0/run/pgpool.pid not readable (yet?) after start.
Nov 14 09:05:13 viya-dev-core0.fcc.ca systemd[1]: Failed to start SAS Infrastructure Data Server Cluster Service sas-viya-sasdatasvrc-postgres for postgres Cluster.
-- Subject: Unit sas-viya-sasdatasvrc-postgres.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit sas-viya-sasdatasvrc-postgres.service has failed.
--
-- The result is failed.
Nov 14 09:05:13 viya-dev-core0.fcc.ca systemd[1]: Unit sas-viya-sasdatasvrc-postgres.service entered failed state.
Nov 14 09:05:13 viya-dev-core0.fcc.ca systemd[1]: sas-viya-sasdatasvrc-postgres.service failed.
Nov 14 09:05:13 viya-dev-core0.fcc.ca sudo[33355]: pam_unix(sudo:session): session closed for user root
Nov 14 09:06:13 viya-dev-core0.fcc.ca sshd[15307]: Received disconnect from 10.122.249.138 port 35918:11: disconnected by user
Nov 14 09:06:13 viya-dev-core0.fcc.ca sshd[15307]: Disconnected from 10.122.249.138 port 35918
Nov 14 09:06:13 viya-dev-core0.fcc.ca sshd[15303]: pam_unix(sshd:session): session closed for user sas
Nov 14 09:06:13 viya-dev-core0.fcc.ca systemd-logind[8856]: Removed session 33.
-- Subject: Session 33 has been terminated
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: http://www.freedesktop.org/wiki/Software/systemd/multiseat
--
-- A session with the ID 33 has been terminated.
Nov 14 09:06:36 viya-dev-core0.fcc.ca amazon-ssm-agent[10176]: 2018-11-14 09:06:36 INFO [HealthCheck] HealthCheck reporting agent health.
Nov 14 09:07:37 viya-dev-core0.fcc.ca chronyd[8869]: Source 2001:19f0:5:5626:5400:1ff:feb3:9e6e replaced with 149.28.39.34
Nov 14 09:09:29 viya-dev-core0.fcc.ca amazon-ssm-agent[10176]: 2018-11-14 09:09:29 INFO [MessagingDeliveryService] [Association] Next association is scheduled at 2018-11-15 08:09:25 +0000 UTC, system will sleep for 16h59m55.323726317s
Nov 14 09:09:30 viya-dev-core0.fcc.ca amazon-ssm-agent[10176]: 2018-11-14 09:09:30 INFO [LongRunningPluginsManager] There are no long running plugins currently getting executed - skipping their healthcheck
Nov 14 09:11:36 viya-dev-core0.fcc.ca amazon-ssm-agent[10176]: 2018-11-14 09:11:36 INFO [HealthCheck] HealthCheck reporting agent health.
Nov 14 09:14:29 viya-dev-core0.fcc.ca amazon-ssm-agent[10176]: 2018-11-14 09:14:29 INFO [MessagingDeliveryService] [Association] Next association is scheduled at 2018-11-15 08:09:25 +0000 UTC, system will sleep for 16h54m55.32373882s
Nov 14 09:14:37 viya-dev-core0.fcc.ca amazon-ssm-agent[10176]: 2018-11-14 09:14:37 INFO [MessagingDeliveryService] [Association] Based upon expression rate(1 day) and last execution date 2018-11-14T08-09-25.000Z, next scheduled date f
Nov 14 09:14:37 viya-dev-core0.fcc.ca amazon-ssm-agent[10176]: 2018-11-14 09:14:37 INFO [MessagingDeliveryService] [Association] Scheduling association 92e59326-0a89-44f0-803a-b030fe3a70d3, setting next ScheduledDate to 2018-11-15T08-
Nov 14 09:14:38 viya-dev-core0.fcc.ca amazon-ssm-agent[10176]: 2018-11-14 09:14:37 INFO [MessagingDeliveryService] [Association] Schedule manager refreshed with 1 associations, 0 new associations associated
Nov 14 09:14:38 viya-dev-core0.fcc.ca amazon-ssm-agent[10176]: 2018-11-14 09:14:37 INFO [MessagingDeliveryService] [Association] Next association is scheduled at 2018-11-15 08:09:25 +0000 UTC, system will sleep for 16h54m47.143804802s
[root@viya-dev-core0 bin]#

---------end----------

**Comment by alexal** [comment]
@JayKyle01 As I said in the track, please try to start SAS Viya using a standard procedure described on this page: [https://go.documentation.sas.com/?cdcId=calcdc&cdcVersion=3.4&docsetId=calchkadm&docsetTarget=n00003ongoingtasks00000admin.htm&locale=en ](url)

**Comment by alexal** [comment]
This issue has been resolved.

**Comment by AlissaSchleich** [comment]
We think this issue is resolved.   Please open an issue in the new SAS Viya Ark repository if you are still having problems.

**Comment by smockroll** [comment]
Hi, the link does not work. What was the resolution for the issue?

**Comment by erharb** [comment]
@smockroll looks like the link text was correct, but the link href was bad. This should work:

 https://go.documentation.sas.com/?cdcId=calcdc&cdcVersion=3.4&docsetId=calchkadm&docsetTarget=n00003ongoingtasks00000admin.htm&locale=en

**Comment by smockroll** [comment]
thank @erharb . Done
