### ISSUE TITLE
Revert changes performed via virk viya 3.4

### ISSUE THREAD

**Issue by JoNicolas** [sassoftware/virk#97]
Hello Team,

I had to deploy SAS Viya 3.4 on one of our environment, in order to be compatible for this operation, I used the Ansible virk playbook to check and deploy settings.

This virk deployment was successful and after our test of Viya 3.4, I had to uninstall Viya. The process is well documented in the administration guide and was performed easily. 

However, how can I revert back changes performed through Virk playbook ?

Thanks for your help.

Best regards,

Nicolas

**Comment by thpang** [comment]
@JoNicolas once the Virk playbook has been run, the modifications it has made would be good for all subsequent Viya installs. Even if you remove the Viya software the OS/Software adjustments the Virk playbook made will still be valid. Is there a need to rollback the system to its original state prior to running the Virk playbook? Just wondering what your use case is here and the possible need. Thanks in advance.

**Comment by AlissaSchleich** [comment]
We are not planning to implement reversing Viya Playbook actions.
