### ISSUE TITLE
Add jq to VI VIRK

### ISSUE THREAD

**Issue by henriquevaskys** [sassoftware/virk#98]
Hi

I realized that jq was not added to VIRK for VI installs. Would you please add it?

There are 2 options:

1 - assign EPEL repo and do a simple  yum install jq

2 - Download and copy to /usr/bin on all servers (see below)
https://go.documentation.sas.com/?docsetId=dplyml0phy0lax&docsetTarget=n0zjykknqs5ln6n1292uvye8ucrb.htm&docsetVersion=3.4&locale=en#n0rb33plg9ipqgn11a1dboifeiof

Thank you,
Henri

**Comment by henriquevaskys** [comment]
I created the following code below. I did not submit as a pull request as there's no branch yet for VI pre-requisites.

/*/*/*/*/
in defaults/main.yml, add the following to the bottor
/*/*/*/*/

## jq Install
jq_bin: /usr/bin/jq



/*/*/*/*/
in tasks/main.yml add the following before the last line
/*/*/*/*/
- include: pre.jq_install.yml


/*/*/*/*/
create a new file named tasks/pre.jq_install.yml and add the following content.
/*/*/*/*/
---
####################################################################
## jq Install
####################################################################

- block:

  - name: "Check if {{jq_bin}} file exists"
    stat:
      path: "{{jq_bin}}"
    check_mode: no
    register: jq_bin_exists

  - debug: var=jq_bin_exists

  - name: "Download jq into /tmp"
    get_url:
      url: https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64
      dest: "{{jq_bin}}"
      group: root
      owner: root
      mode: 0755
    when: not jq_bin_exists.stat.exists

  ## block end
  tags:
    - jq_install

**Comment by kevinlinglesas** [comment]
This issue was fixed in [Viya ARK github repo](https://github.com/sassoftware/viya-ark), release [Viya34-ark-1.3](https://github.com/sassoftware/viya-ark/releases/tag/Viya34-ark-1.3).   VI support was added in [Viya34-ark-1.2](https://github.com/sassoftware/viya-ark/releases/tag/Viya34-ark-1.2) (see DEPENB-1635 in the release notes), but a bug fix was required so Viya34-ark-1.3 is the release to download.
